### ISSUE TITLE
INVERTED MY COLORS PLS FIX

### ISSUE THREAD

**Issue by Jwiz33** [TheToxicRyu/Waifu-to-life-machine#1]
thx m8

**Comment by TheToxicRyu** [comment]
What did your waifu say when it was inverted?

**Comment by Jwiz33** [comment]
She called me a "nigger"

**Comment by TheToxicRyu** [comment]
Looks lkie anti piracy protection was enabled. Try deleting ur sysNAND

**Comment by Jwiz33** [comment]
now wen 3ds truned on it saiz erroe 2x5437 gayway brik lolz

**Comment by TheToxicRyu** [comment]
nou through yew 3DZ in teh Trash fixd

**Comment by Jwiz33** [comment]
walks noew thaencxs
